name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Step 3: Pull chatbot Docker image
      - name: Pull chatbot Docker image
        run: |
          docker pull samuel1234567/chatbot-image:latest

      # Step 4: Run chatbot container
      - name: Run chatbot container
        run: |
          docker run -d --name chatbot-container -p 5005:5005 samuel1234567/chatbot-image:latest
          
          # Wait for the chatbot service to be ready
          echo "Waiting for the chatbot service..."
          until curl -s http://localhost:5005/webhooks/rest/webhook; do
            echo "Chatbot not ready yet, retrying in 5 seconds..."
            sleep 5
          done
          echo "Chatbot is ready."

      # Step 5: Run MySQL database check in the Docker container
      - name: Check MySQL database inside the container
        run: |
          # Ensure MySQL is running
          docker exec -it chatbot-container bash -c "mysql -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e 'SHOW DATABASES;'"
          
          # Replace 'test_db' with your actual database name
          docker exec -it chatbot-container bash -c "mysql -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e 'USE test_db; SHOW TABLES;'"

          # Optionally, view some rows in a specific table
          docker exec -it chatbot-container bash -c "mysql -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e 'USE test_db; SELECT * FROM users LIMIT 10;'"

      # Step 6: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 7: Install dependencies
      - name: Install dependencies
        run: |
          # Create and activate a virtual environment
          python -m venv venv
          source venv/bin/activate
          pip install -r Flask-Website/requirements.txt
          pip install flask_babel
          
          # Also install coverage and pytest to run tests and measure coverage
          pip install coverage pytest

      # Step 8: Create config.py from GitHub Secrets
      - name: Create config.py from GitHub Secrets
        run: |
          echo "Creating config.py file from secrets..."
          echo "DB_CONFIG = ${DB_CONFIG}" > Flask-Website/Database/config.py
          # Validate syntax to ensure proper formatting
          python -m py_compile Flask-Website/Database/config.py
        env:
          DB_CONFIG: ${{ secrets.DB_CONFIG }}

      # Step 9: Debug config.py
      - name: Debug config.py
        run: |
          echo "Contents of config.py:"
          cat Flask-Website/Database/config.py | sed 's/password.*/password: ***}/g'

      # Step 10: Run tests and generate coverage report
      - name: Run tests and generate coverage report
        run: |
          # Run tests with coverage collection
          source venv/bin/activate
          export PYTHONPATH=Flask-Website
          coverage run -m pytest
          
          # Generate a report in multiple formats
          coverage report  # Text-based report
          coverage html  # HTML report for local use
          
          # Generate the LCOV report for SonarCloud analysis
          mkdir -p coverage-reports  # Create a folder to store coverage report
          coverage lcov > coverage-reports/coverage.lcov  # Save coverage in LCOV format
          
          # Optionally check the generated coverage report
          ls -la coverage-reports

      # Step 11: Analyze with SonarCloud
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
        with:
          # Additional arguments for the SonarScanner CLI
          args:
            -Dsonar.projectKey=dogface3_AI-Chatbot
            -Dsonar.organization=dogface3
            -Dsonar.sources=Flask-Website
            -Dsonar.projectBaseDir=.
            -Dsonar.exclusions=Flask-Website/mynev/**
            -Dsonar.python.coverage.reportPaths=coverage-reports/coverage.lcov  # Provide path to LCOV report for coverage analysis
